version: '3.7'

services:
  docker_example_dagit:
    build:
      context: .
      dockerfile: ./threatintel/Dockerfile
    entrypoint:
      - dagit
      - -f
      - "worker/worker_actualization.py"
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
    expose:
      - "3000"
    ports:
      - "3000:3000"
  enrichment:
    build:
      dockerfile: threatintel/Dockerfile_Enrichment
      context: .
    volumes:
      - ./threatintel/:/usr/src/app/
    env_file:
      - ./threatintel/.env
  worker:
    build:
      dockerfile: threatintel/Dockerfile_Worker
      context: .
    volumes:
      - ./threatintel/:/usr/src/app/
    env_file:
      - ./threatintel/.env
