psvc:
  name: Воркер актуализации скоринга
  description: Воркер актуализации скоринга, обогащения инфромацией и удаление архивных индикаторов

replicaCount: 1

resources:
  limits:
    memory: 1Gi
    cpu: 1
  requests:
    memory: 512Mi
    cpu: 100m

databases:
  - id: DATABASE_1
    type: POSTGRESQL
    host: 10.7.77.7
    port: 5432
    name: mydb

strategyType: Recreate