psvc:
  name: Воркер актуализации скоринга
  description: Воркер актуализации скоринга, обогащения инфромацией и удаление архивных индикаторов

replicaCount: 1

resources:
  limits:
    memory: 1Gi
    cpu: 1
  requests:
    memory: 512Mi
    cpu: 100m

databases:
  - type: POSTGRESQL
    host: 10.7.27.113
    port: 5432
    name: db


strategyType: Recreate
